/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yage_raspberry_DHT_jni */

#ifndef _Included_com_yage_raspberry_DHT_jni
#define _Included_com_yage_raspberry_DHT_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yage_raspberry_DHT_jni
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_yage_raspberry_DHT_1jni_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_yage_raspberry_DHT_jni
 * Method:    readDHTData
 * Signature: (Lcom/yage/raspberry/DHT_data;)I
 */
JNIEXPORT jint JNICALL Java_com_yage_raspberry_DHT_1jni_readDHTData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
