/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DHT_jni */

#ifndef _Included_DHT_jni
#define _Included_DHT_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DHT_jni
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DHT_1jni_init
  (JNIEnv *, jobject);

/*
 * Class:     DHT_jni
 * Method:    readDHTData
 * Signature: (LDHT_data;)I
 */
JNIEXPORT jint JNICALL Java_DHT_1jni_readDHTData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
